#!/bin/sh
# =========================================================================
# MerlinOS Boot Splash Script
# =========================================================================
#
# This script executes during the early stages of the systemd boot process.
# Its primary purpose is to clear the initial terminal output, display a
# custom ASCII art logo (the "boot splash"), and silence subsequent kernel
# and system messages from overwriting the logo during the boot sequence.
#
# It writes the boot logo directly to /etc/issue, which is the file read
# and displayed by 'getty' prompts before login.
# =========================================================================

# --- 1. Define Target Console ---
# Set the primary console device where the boot output is expected to appear.
# /dev/tty1 is the first virtual console (the screen you see when booting).
CONSOLE="/dev/tty1"

# --- 2. Clear Previous Output ---
# Clear any existing text on the screen to provide a blank canvas for our logo.
# We redirect the output of 'clear' directly to the target console.
clear > $CONSOLE


# --- 3. Write Boot Splash to /etc/issue ---
# Use a "Here Document" (cat << EOF) to write our ASCII art and branding text directly
# into /etc/issue. The login manager reads this file just before presenting the login prompt.
cat << "EOF" > /etc/issue

MM  MM  EEEEEE  RRRR    LL      II  NN  N   OOO    SSSS  
M MM M  EE      R   R   LL      II  N N N  O   O  S      
M    M  EEEE    RRRR    LL      II  N  NN  O   O   SSS   
M    M  EE      R  R    LL      II  N   N  O   O      S
M    M  EEEEEE  R   R   LLLLLL  II  N   N   OOO   SSSS                                                                                                                                                                                                                                                                                                                                       
                                                      
UElement Softwares / MerlinOS v1.0
EOF


# cat << "EOF" > /etc/issue

# M   M  EEE  RRR  L   I  N N  OOO  SSS   L   I  TTT  EEE
# MM MM  E    R  R L   I  NNN  O O  S     L   I   T   E
# M M M  EE   RRR  L   I  N N  O O  SSS   L   I   T   EE
# M   M  E    R R  L   I  N N  O O    S   L   I   T   E
# M   M  EEE  R  R LLL I  N N  OOO  SSS   LLL I   T   EEE      
 
                                                      
# UElement Softwares / MerlinLiteOS v1.0
# EOF



# 3. Silence kernel noise to prevent it from overwriting the logo
dmesg -n 1

# --- 5. Silence Future Script Output ---
# This ensures that any standard output (stdout) or error output (stderr)
# generated by commands executed AFTER this point in the script are sent
# to the void (/dev/null), preventing them from polluting the screen.
exec >/dev/null 2>&1