MACHINE = "raspberrypi3-64"
DISTRO = "MerlinOS"

TMPDIR = "${TOPDIR}/tmp-${BB_CURRENT_MC}"

# Raspberry Pi Hardware Config
IMAGE_FSTYPES = "wic.bz2"
WKS_FILE = "merlin-drone.wks"
ENABLE_UART = "1"
DISABLE_RPI_BOOT_LOGO = "1"
ARM_KEEP_ALIVE = "1"
APPEND:append = " fastboot panic=5"
APPEND:append:raspberrypi4 = " isolcpus=3"
SERIAL_CONSOLES = "115200;ttyAMA0 115200;tty1"
SERIAL_CONSOLES_CHECK = ""

IMAGE_INSTALL:append = " \
    custom-boot \
    packagegroup-custom-core \
    packagegroup-custom-net \
    packagegroup-custom-python \
    packagegroup-custom-tools \
    packagegroup-llm-package \
    ssh-pregen-hostkeys \
    rng-tools \
    rt-tests \
    sysstat \
    iotop \
    procps \
"