MACHINE = "qemuarm64"
DISTRO = "MerlinOS"
DISTRO_NAME:forcevariable = "MerlinOS"
DISTRO_VERSION:forcevariable = "1.0"
QB_KERNEL_CMDLINE_APPEND += " console=ttyAMA0,115200 --noclear"

IMAGE_INSTALL:append = " \
    custom-boot \
    packagegroup-custom-core \
    packagegroup-custom-net \
    packagegroup-custom-python \
    packagegroup-custom-tools \
    packagegroup-llm-package \
"

# Prevents getty from clearing the screen, keeping your ASCII art visible
SERIAL_CONSOLES_CHECK = ""


# Appends 'quiet' to the kernel command line to hide boot logs
# quiet: silences kernel
# systemd.show_status=false: silences the [ OK ] messages
# loglevel=0: hides almost all kernel noise
# console=ttyAMA0: keeps it on the serial port but quiet
QB_KERNEL_CMDLINE_APPEND += " quiet splash loglevel=0 systemd.show_status=false rd.udev.log_level=0 vt.global_cursor_default=0"


# ---------------------------------------------------------
# MERLINOS VIRTUAL HARDWARE UPGRADE
# ---------------------------------------------------------
# Allocate 8GB of RAM
QB_MEM = "-m 8192"

# Allocate 6 CPU Cores
QB_SMP = "-smp 6"

# Fix the serial console for nographic mode
SERIAL_CONSOLES = "115200;ttyAMA0"

# This line ensures the 'mem=4M' bug is overridden by your 4GB setting
QB_KERNEL_CMDLINE_APPEND += " mem=4G"