# meta-kos-core/conf/distro/knowledgeos.conf
DISTRO = "knowledgeos"
DISTRO_NAME = "KnowledgeOS"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "horizon"

# Inherit from OE-Core base instead of Poky
include conf/distro/defaultsetup.conf

# Branding
BASEFS_IMAGE_BANNER = "KnowledgeOS 1.0 \\n \\l"
hostname_pn-base-files = "knowledgeos"

# System Management
INIT_MANAGER = "systemd"
DISTRO_FEATURES:append = " systemd pam opengl virtualization"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

# Enable uninative to support pre-compiled tools like Bazel
INHERIT += "uninative"

# Development & Licensing
LICENSE_FLAGS_ACCEPTED += "commercial"